1. Installing required

In [2]:
!pip install pandas numpy openpyxl tqdm

Requirement already satisfied: pandas in .\.jupyter\New folder\envs\synthetic\Lib\site-packages (2.3.3)
Requirement already satisfied: numpy in .\.jupyter\New folder\envs\synthetic\Lib\site-packages (2.4.6)
Requirement already satisfied: openpyxl in .\.jupyter\New folder\envs\synthetic\Lib\site-packages (3.1.5)
Requirement already satisfied: tqdm in .\.jupyter\New folder\envs\synthetic\Lib\site-packages (4.69.1)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.jupyter\New folder\envs\synthetic\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\.jupyter\New folder\envs\synthetic\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in .\.jupyter\New folder\envs\synthetic\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: et-xmlfile in .\.jupyter\New folder\envs\synthetic\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: colorama in .\.jupyter\New folder\envs\synthetic\Lib\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: six>=1.5 in .\.jupyter\New folder\envs\synthetic\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

2. Import Libraries

In [3]:
import pandas as pd
import numpy as np
from pathlib import Path
from tqdm import tqdm

print("Libraries loaded successfully.")

Libraries loaded successfully.

3. Folder path

In [4]:
cert_folder = Path(r"C:\Users\Admin\Downloads\r4.2\r4.2")

4. defining the files

In [5]:
from pathlib import Path

cert_folder = Path(r"C:\Users\Admin\Downloads\r4.2\r4.2")

logon_file = cert_folder / "logon.csv"
device_file = cert_folder / "device.csv"
file_file = cert_folder / "file.csv"
email_file = cert_folder / "email.csv"
http_file = cert_folder / "http.csv"

# LDAP is a folder, not a single file
ldap_folder = cert_folder / "LDAP"

print("Files linked successfully.")

Files linked successfully.

5. Reading employees information

In [6]:
from pathlib import Path

cert_folder = Path(r"C:\Users\Admin\Downloads\r4.2\r4.2")
ldap_folder = cert_folder / "LDAP"

print("LDAP folder exists:", ldap_folder.exists())

print("\nContents of the LDAP folder:")
for file in ldap_folder.iterdir():
    print(file.name)

LDAP folder exists: True

Contents of the LDAP folder:
2009-12.csv
2010-01.csv
2010-02.csv
2010-03.csv
2010-04.csv
2010-05.csv
2010-06.csv
2010-07.csv
2010-08.csv
2010-09.csv
2010-10.csv
2010-11.csv
2010-12.csv
2011-01.csv
2011-02.csv
2011-03.csv
2011-04.csv
2011-05.csv

In [7]:
# LDAP folder
ldap_folder = Path(r"C:\Users\Admin\Downloads\r4.2\r4.2\LDAP")

# Find all CSV files
ldap_files = sorted(ldap_folder.glob("*.csv"))

print("Number of LDAP files found:", len(ldap_files))

employee_tables = []

for file in ldap_files:
    print("Reading:", file.name)

    df = pd.read_csv(file)

    employee_tables.append(df)

# Combine all monthly LDAP files
employees = pd.concat(employee_tables, ignore_index=True)

print("\nEmployee Dataset Shape:", employees.shape)

employees.head()

Number of LDAP files found: 18
Reading: 2009-12.csv
Reading: 2010-01.csv
Reading: 2010-02.csv
Reading: 2010-03.csv
Reading: 2010-04.csv
Reading: 2010-05.csv
Reading: 2010-06.csv
Reading: 2010-07.csv
Reading: 2010-08.csv
Reading: 2010-09.csv
Reading: 2010-10.csv
Reading: 2010-11.csv
Reading: 2010-12.csv
Reading: 2011-01.csv
Reading: 2011-02.csv
Reading: 2011-03.csv
Reading: 2011-04.csv
Reading: 2011-05.csv

Employee Dataset Shape: (16743, 9)

,employee_name,user_id,email,role,business_unit,functional_unit,department,team,supervisor
0,Calvin Edan Love,CEL0561,Calvin.Edan.Love@dtaa.com,ComputerProgrammer,1,2 - ResearchAndEngineering,2 - SoftwareManagement,3 - Software,Stephanie Briar Harrington
1,Christine Reagan Deleon,CRD0624,Christine.Reagan.Deleon@dtaa.com,Salesman,1,5 - SalesAndMarketing,2 - Sales,3 - RegionalSales,Winter Veda Burks
2,Jade Felicia Caldwell,JFC0557,Jade.Felicia.Caldwell@dtaa.com,SoftwareEngineer,1,2 - ResearchAndEngineering,2 - SoftwareManagement,3 - Software,Stephanie Briar Harrington
3,Aquila Stewart Dejesus,ASD0577,Aquila.Stewart.Dejesus@dtaa.com,ProductionLineWorker,1,3 - Manufacturing,3 - Assembly,3 - AssemblyDept,Whilemina Pandora England
4,Micah Abdul Rojas,MAR0955,Micah.Abdul.Rojas@dtaa.com,ProductionLineWorker,1,3 - Manufacturing,3 - Assembly,6 - AssemblyDept,Sandra Beverly Diaz

In [8]:
print(employees.columns)

Index(['employee_name', 'user_id', 'email', 'role', 'business_unit',
       'functional_unit', 'department', 'team', 'supervisor'],
      dtype='object')

**keeping only useful columns

In [9]:
employees = employees[
    [
        "user_id",
        "role",
        "department"
    ]
].copy()

employees.head()

   user_id                  role              department
0  CEL0561    ComputerProgrammer  2 - SoftwareManagement
1  CRD0624              Salesman               2 - Sales
2  JFC0557      SoftwareEngineer  2 - SoftwareManagement
3  ASD0577  ProductionLineWorker            3 - Assembly
4  MAR0955  ProductionLineWorker            3 - Assembly

6. Creation ofthr DBE employee information

In [10]:
import numpy as np

np.random.seed(42)

exam_roles = [
    "Chief Examination Officer",
    "Senior Examination Officer",
    "Provincial Examination Coordinator",
    "Printing Technician",
    "Warehouse Officer",
    "ICT Administrator",
    "Data Capturer"
]

dbe_departments = [
    "Question Paper Development",
    "Secure Printing",
    "Logistics",
    "Results Processing",
    "Provincial Office",
    "Examination Administration"
]

provinces = [
    "Gauteng",
    "Limpopo",
    "Mpumalanga",
    "Free State",
    "North West",
    "KwaZulu-Natal",
    "Western Cape",
    "Eastern Cape",
    "Northern Cape"
]

subjects = [
    "Mathematics",
    "Mathematical Literacy",
    "Physical Sciences",
    "Life Sciences",
    "Accounting",
    "English FAL",
    "English HL",
    "Business Studies",
    "Geography"
]

employees["role"] = np.random.choice(exam_roles, len(employees))

employees["province"] = np.random.choice(provinces, len(employees))

employees["department"] = np.random.choice(
    dbe_departments,
    len(employees)
)

employees["subject_permission"] = np.random.choice(
    subjects,
    len(employees)
)

employees.head()

,user_id,role,department,province,subject_permission
0,CEL0561,Data Capturer,Examination Administration,North West,Life Sciences
1,CRD0624,Printing Technician,Logistics,Free State,Business Studies
2,JFC0557,Warehouse Officer,Question Paper Development,Eastern Cape,English FAL
3,ASD0577,Data Capturer,Provincial Office,Gauteng,Mathematical Literacy
4,MAR0955,Provincial Examination Coordinator,Results Processing,North West,Mathematical Literacy

In [37]:
duplicates = employees["user_id"].duplicated().sum()

print("Duplicate user IDs:", duplicates)

Duplicate user IDs: 15743

In [38]:
employees = employees.drop_duplicates(
    subset="user_id",
    keep="last"
)

print("Employee rows:", employees.shape)

print("Unique employees:", employees["user_id"].nunique())

Employee rows: (1000, 5)
Unique employees: 1000

In [46]:
print(employees.shape)

print(employees["user_id"].nunique())

(1000, 5)
1000

In [47]:
activities["user_id"] = activities["user_id"].astype(str)

employees["user_id"] = employees["user_id"].astype(str)

C:\Users\Admin\AppData\Local\Temp\ipykernel_26000\2764561571.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  employees["user_id"] = employees["user_id"].astype(str)

SECTION 2: ATTACHING SECTION 1 INFORMATION TO EVERY CERT ACTIVITY

7. Loading the CERT activity logs

In [48]:
import pandas as pd

ROWS = 10000      # You can increase later to 50000 or 100000

logon = pd.read_csv(logon_file, nrows=ROWS)
device = pd.read_csv(device_file, nrows=ROWS)
file_access = pd.read_csv(file_file, nrows=ROWS)
email = pd.read_csv(email_file, nrows=ROWS)
http = pd.read_csv(http_file, nrows=ROWS)

print("Datasets loaded successfully!")

print(logon.shape)
print(device.shape)
print(file_access.shape)
print(email.shape)
print(http.shape)

Datasets loaded successfully!
(10000, 5)
(10000, 5)
(10000, 6)
(10000, 11)
(10000, 6)

8. Making all files to have the same columns

In [49]:
logon = logon.rename(columns={
    "date":"timestamp",
    "user":"user_id",
    "pc":"location"
})

device = device.rename(columns={
    "date":"timestamp",
    "user":"user_id",
    "pc":"location"
})

file_access = file_access.rename(columns={
    "date":"timestamp",
    "user":"user_id",
    "pc":"location"
})

email = email.rename(columns={
    "date":"timestamp",
    "user":"user_id",
    "pc":"location",
    "to":"to_email",
    "from":"from_email"
})

http = http.rename(columns={
    "date":"timestamp",
    "user":"user_id",
    "pc":"location"
})

9. Creating one activity column

In [50]:
logon["action"] = "Logon"

device["action"] = "USB Device"

file_access["action"] = "File Access"

email["action"] = "Email"

http["action"] = "Web Browsing"

10. creating the missing columns

In [51]:
logon["filename"] = None
logon["url"] = None
logon["to_email"] = None
logon["from_email"] = None

device["filename"] = None
device["url"] = None
device["to_email"] = None
device["from_email"] = None

file_access["url"] = None
file_access["to_email"] = None
file_access["from_email"] = None

email["filename"] = None
email["url"] = None

http["filename"] = None
http["to_email"] = None
http["from_email"] = None

11. Keeping all useful columns

In [52]:
columns = [
    "timestamp",
    "user_id",
    "location",
    "action",
    "filename",
    "url",
    "to_email",
    "from_email"
]

logon = logon[columns]

device = device[columns]

file_access = file_access[columns]

email = email[columns]

http = http[columns]

In [53]:
print(logon.shape)
print(device.shape)
print(file_access.shape)
print(email.shape)
print(http.shape)

(10000, 8)
(10000, 8)
(10000, 8)
(10000, 8)
(10000, 8)

12. Combining all the files

In [54]:
activities = pd.concat(
    [logon, device, file_access, email, http],
    ignore_index=True
)

print(activities.shape)

activities.head()

(50000, 8)

,timestamp,user_id,location,action,filename,url,to_email,from_email
0,01/02/2010 06:49:00,NGF0157,PC-6056,Logon,None,None,None,None
1,01/02/2010 06:50:00,LRR0148,PC-4275,Logon,None,None,None,None
2,01/02/2010 06:53:04,LRR0148,PC-4124,Logon,None,None,None,None
3,01/02/2010 07:00:00,IRM0931,PC-7188,Logon,None,None,None,None
4,01/02/2010 07:00:00,MOH0273,PC-6699,Logon,None,None,None,None

13. Combining the activity data frame with the employee

In [55]:
activities = activities.merge(
    employees,
    on="user_id",
    how="left"
)

print(activities.shape)

activities.head()

(50000, 12)

,timestamp,user_id,location,action,filename,url,to_email,from_email,role,department,province,subject_permission
0,01/02/2010 06:49:00,NGF0157,PC-6056,Logon,None,None,None,None,Senior Examination Officer,Results Processing,North West,Geography
1,01/02/2010 06:50:00,LRR0148,PC-4275,Logon,None,None,None,None,Data Capturer,Logistics,Gauteng,English FAL
2,01/02/2010 06:53:04,LRR0148,PC-4124,Logon,None,None,None,None,Data Capturer,Logistics,Gauteng,English FAL
3,01/02/2010 07:00:00,IRM0931,PC-7188,Logon,None,None,None,None,ICT Administrator,Examination Administration,Western Cape,Business Studies
4,01/02/2010 07:00:00,MOH0273,PC-6699,Logon,None,None,None,None,Warehouse Officer,Examination Administration,Northern Cape,Physical Sciences

In [56]:
print(activities.isnull().sum())

timestamp                 0
user_id                   0
location                  0
action                    0
filename              40000
url                   40000
to_email              40000
from_email            40000
role                      0
department                0
province                  0
subject_permission        0
dtype: int64

14. Saving the dataset

In [57]:
activities.to_csv(
    "DBE_Employee_Activities.csv",
    index=False
)

print("Notebook 3 completed and dataset saved.")

Notebook 3 completed and dataset saved.