1. Load libraries

In [4]:
import pandas as pd
import numpy as np

from sdv.metadata import SingleTableMetadata
from sdv.single_table import GaussianCopulaSynthesizer

print("Libraries loaded successfully.")

Libraries loaded successfully.

2. Load the preprocessed Cert dataset

In [5]:
data = pd.read_csv(
    r"C:\Users\Admin\OneDrive - Sol Plaatje University\Documents\cert_preprocessed.csv"
)

print("Dataset loaded successfully.")
print("Shape:", data.shape)

data.head()

Dataset loaded successfully.
Shape: (248301, 17)

,timestamp,user_id,location,action,hour,day,month,weekday,after_hours,employee_name,email,role,business_unit,functional_unit,department,team,supervisor
0,2010-01-02 06:49:00,NGF0157,PC-6056,logon,6,2,1,Saturday,0,Nissim Gil French,Nissim.Gil.French@dtaa.com,FinancialAnalyst,1,4 - Finance,3 - FinancialPlanning,Unknown,Libby Rosalyn Richard
1,2010-01-02 06:50:00,LRR0148,PC-4275,logon,6,2,1,Saturday,0,Libby Rosalyn Richard,Libby.Rosalyn.Richard@dtaa.com,Manager,1,4 - Finance,3 - FinancialPlanning,Unknown,Thomas Vladimir Stokes
2,2010-01-02 06:53:04,LRR0148,PC-4124,logon,6,2,1,Saturday,0,Libby Rosalyn Richard,Libby.Rosalyn.Richard@dtaa.com,Manager,1,4 - Finance,3 - FinancialPlanning,Unknown,Thomas Vladimir Stokes
3,2010-01-02 07:00:00,IRM0931,PC-7188,logon,7,2,1,Saturday,0,Ignatius Reese Morton,Ignatius.Reese.Morton@dtaa.com,ComputerProgrammer,1,2 - ResearchAndEngineering,2 - SoftwareManagement,6 - Software,Caleb Mason Ball
4,2010-01-02 07:00:00,MOH0273,PC-6699,logon,7,2,1,Saturday,0,Macaulay Otto Hopkins,Macaulay.Otto.Hopkins@dtaa.com,HardwareEngineer,1,2 - ResearchAndEngineering,3 - Engineering,4 - SystemsEngineering,Gage Kaden Odonnell

3. Check missing values

In [6]:
print(data.isnull().sum())

timestamp          0
user_id            0
location           0
action             0
hour               0
day                0
month              0
weekday            0
after_hours        0
employee_name      0
email              0
role               0
business_unit      0
functional_unit    0
department         0
team               0
supervisor         0
dtype: int64

4. Convert the timestamp to datetime

In [7]:
data["timestamp"] = pd.to_datetime(data["timestamp"])

print(data.dtypes)

timestamp          datetime64[ns]
user_id                    object
location                   object
action                     object
hour                        int64
day                         int64
month                       int64
weekday                    object
after_hours                 int64
employee_name              object
email                      object
role                       object
business_unit               int64
functional_unit            object
department                 object
team                       object
supervisor                 object
dtype: object

5. Creation of metadata

In [8]:
metadata = SingleTableMetadata()

metadata.detect_from_dataframe(data)

print("Metadata created successfully.")

Metadata created successfully.

6. Building Gaussian Copula Model

In [9]:
gaussian = GaussianCopulaSynthesizer(
    metadata=metadata
)

print("Gaussian Copula model created.")

Gaussian Copula model created.

C:\Users\Admin\.jupyter\New folder\envs\synthetic\Lib\site-packages\sdv\single_table\base.py:183: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\Admin\.jupyter\New folder\envs\synthetic\Lib\site-packages\sdv\single_table\base.py:139: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

7. Train the Gaussian Copula model created

In [10]:
gaussian.fit(data)

print("Training completed successfully.")

Training completed successfully.

8. Generate synthetic data

In [11]:
synthetic_gaussian = gaussian.sample(
    num_rows=len(data)
)

print("Synthetic dataset generated.")

Synthetic dataset generated.

9. viewing the dataset

In [12]:
synthetic_gaussian.head()

,timestamp,user_id,location,action,hour,day,month,weekday,after_hours,employee_name,email,role,business_unit,functional_unit,department,team,supervisor
0,2010-02-09 20:21:52,WDV0573,PC-6390,device,10,19,1,Thursday,0,Illana Yvette Bradshaw,fmartin@example.org,ChiefEngineer,1,5 - SalesAndMarketing,2 - SoftwareManagement,4 - Lab,Sarah Imelda Juarez
1,2010-01-25 20:37:13,PRM0740,PC-0616,email,14,8,1,Monday,0,Steel Solomon Garrison,ubarnett@example.com,Salesman,1,3 - Manufacturing,3 - FieldService,7 - TestAndEvalualtion,Winter Veda Burks
2,2010-01-02 23:35:01,RNF0765,PC-4547,email,15,4,1,Friday,0,Keegan Marvin Benson,mfoster@example.net,MechanicalEngineer,1,2 - ResearchAndEngineering,2 - SoftwareManagement,7 - TestAndEvalualtion,Aurora Tatiana Payne
3,2010-01-04 18:18:37,BBG0325,PC-1476,http,11,13,1,Wednesday,0,Ingrid Irene Atkins,amyvillarreal@example.com,Physicist,1,5 - SalesAndMarketing,3 - Engineering,1 - MechanicalEngineering,Clinton Coby Wolfe
4,2010-01-06 20:09:45,MCD0125,PC-6797,http,10,7,1,Monday,0,Blythe Veda Cooke,robert49@example.net,ITAdmin,1,2 - ResearchAndEngineering,6 - Security,Unknown,Todd Vance Spears

10. shape comparison

In [13]:
print("Original Shape :", data.shape)
print("Synthetic Shape:", synthetic_gaussian.shape)

Original Shape : (248301, 17)
Synthetic Shape: (248301, 17)

In [14]:
synthetic_gaussian.columns

Index(['timestamp', 'user_id', 'location', 'action', 'hour', 'day', 'month',
       'weekday', 'after_hours', 'employee_name', 'email', 'role',
       'business_unit', 'functional_unit', 'department', 'team', 'supervisor'],
      dtype='object')

11. Compare the data types

In [15]:
comparison = pd.DataFrame({
    "Original": data.dtypes,
    "Synthetic": synthetic_gaussian.dtypes
})

comparison

                       Original       Synthetic
timestamp        datetime64[ns]  datetime64[ns]
user_id                  object          object
location                 object          object
action                   object          object
hour                      int64           int64
day                       int64           int64
month                     int64           int64
weekday                  object          object
after_hours               int64           int64
employee_name            object          object
email                    object          object
role                     object          object
business_unit             int64           int64
functional_unit          object          object
department               object          object
team                     object          object
supervisor               object          object

12. Save the synthetic dataset

In [16]:
output_path = r"C:\Users\Admin\OneDrive - Sol Plaatje University\Documents\synthetic_gaussian.csv"

synthetic_gaussian.to_csv(output_path, index=False)

print("Synthetic dataset saved successfully.")
print(output_path)

Synthetic dataset saved successfully.
C:\Users\Admin\OneDrive - Sol Plaatje University\Documents\synthetic_gaussian.csv

13. Comparing the first few rows

In [17]:
print("Original Dataset")
display(data.head())

print("\nSynthetic Dataset")
display(synthetic_gaussian.head())

Original Dataset

,timestamp,user_id,location,action,hour,day,month,weekday,after_hours,employee_name,email,role,business_unit,functional_unit,department,team,supervisor
0,2010-01-02 06:49:00,NGF0157,PC-6056,logon,6,2,1,Saturday,0,Nissim Gil French,Nissim.Gil.French@dtaa.com,FinancialAnalyst,1,4 - Finance,3 - FinancialPlanning,Unknown,Libby Rosalyn Richard
1,2010-01-02 06:50:00,LRR0148,PC-4275,logon,6,2,1,Saturday,0,Libby Rosalyn Richard,Libby.Rosalyn.Richard@dtaa.com,Manager,1,4 - Finance,3 - FinancialPlanning,Unknown,Thomas Vladimir Stokes
2,2010-01-02 06:53:04,LRR0148,PC-4124,logon,6,2,1,Saturday,0,Libby Rosalyn Richard,Libby.Rosalyn.Richard@dtaa.com,Manager,1,4 - Finance,3 - FinancialPlanning,Unknown,Thomas Vladimir Stokes
3,2010-01-02 07:00:00,IRM0931,PC-7188,logon,7,2,1,Saturday,0,Ignatius Reese Morton,Ignatius.Reese.Morton@dtaa.com,ComputerProgrammer,1,2 - ResearchAndEngineering,2 - SoftwareManagement,6 - Software,Caleb Mason Ball
4,2010-01-02 07:00:00,MOH0273,PC-6699,logon,7,2,1,Saturday,0,Macaulay Otto Hopkins,Macaulay.Otto.Hopkins@dtaa.com,HardwareEngineer,1,2 - ResearchAndEngineering,3 - Engineering,4 - SystemsEngineering,Gage Kaden Odonnell

Synthetic Dataset

,timestamp,user_id,location,action,hour,day,month,weekday,after_hours,employee_name,email,role,business_unit,functional_unit,department,team,supervisor
0,2010-02-09 20:21:52,WDV0573,PC-6390,device,10,19,1,Thursday,0,Illana Yvette Bradshaw,fmartin@example.org,ChiefEngineer,1,5 - SalesAndMarketing,2 - SoftwareManagement,4 - Lab,Sarah Imelda Juarez
1,2010-01-25 20:37:13,PRM0740,PC-0616,email,14,8,1,Monday,0,Steel Solomon Garrison,ubarnett@example.com,Salesman,1,3 - Manufacturing,3 - FieldService,7 - TestAndEvalualtion,Winter Veda Burks
2,2010-01-02 23:35:01,RNF0765,PC-4547,email,15,4,1,Friday,0,Keegan Marvin Benson,mfoster@example.net,MechanicalEngineer,1,2 - ResearchAndEngineering,2 - SoftwareManagement,7 - TestAndEvalualtion,Aurora Tatiana Payne
3,2010-01-04 18:18:37,BBG0325,PC-1476,http,11,13,1,Wednesday,0,Ingrid Irene Atkins,amyvillarreal@example.com,Physicist,1,5 - SalesAndMarketing,3 - Engineering,1 - MechanicalEngineering,Clinton Coby Wolfe
4,2010-01-06 20:09:45,MCD0125,PC-6797,http,10,7,1,Monday,0,Blythe Veda Cooke,robert49@example.net,ITAdmin,1,2 - ResearchAndEngineering,6 - Security,Unknown,Todd Vance Spears

14.  Comparing the basic statists

In [18]:
print("Original Dataset Statistics")
display(data.describe(include="all"))

print("\nSynthetic Dataset Statistics")
display(synthetic_gaussian.describe(include="all"))

Original Dataset Statistics

,timestamp,user_id,location,action,hour,day,month,weekday,after_hours,employee_name,email,role,business_unit,functional_unit,department,team,supervisor
count,248301,248301,248301,248301,248301.000000,248301.000000,248301.000000,248301,248301.000000,248301,248301,248301,248301.0,248301,248301,248301,248301
unique,NaN,1000,1002,5,NaN,NaN,NaN,7,NaN,1000,1000,42,NaN,7,23,39,68
top,NaN,HSB0196,PC-8001,logon,NaN,NaN,NaN,Monday,NaN,Hadley Sonya Bowen,Hadley.Sonya.Bowen@dtaa.com,Salesman,NaN,2 - ResearchAndEngineering,2 - Sales,Unknown,Hashim Damon Dudley
freq,NaN,2524,2530,50000,NaN,NaN,NaN,86970,NaN,2524,2524,50535,NaN,88322,52811,36496,11419
mean,2010-01-17 02:16:04.649953280,NaN,NaN,NaN,11.791084,11.002392,1.180015,NaN,0.044893,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
min,2010-01-02 06:49:00,NaN,NaN,NaN,0.000000,1.000000,1.000000,NaN,0.000000,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
25%,2010-01-04 16:49:13,NaN,NaN,NaN,9.000000,4.000000,1.000000,NaN,0.000000,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
50%,2010-01-11 12:06:26,NaN,NaN,NaN,11.000000,8.000000,1.000000,NaN,0.000000,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
75%,2010-01-26 07:00:43,NaN,NaN,NaN,15.000000,17.000000,1.000000,NaN,0.000000,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
max,2010-02-26 09:59:44,NaN,NaN,NaN,23.000000,31.000000,2.000000,NaN,1.000000,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,3.647562,7.773622,0.384201,NaN,0.207070,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN

Synthetic Dataset Statistics

,timestamp,user_id,location,action,hour,day,month,weekday,after_hours,employee_name,email,role,business_unit,functional_unit,department,team,supervisor
count,248301,248301,248301,248301,248301.000000,248301.000000,248301.000000,248301,248301.000000,248301,248301,248301,248301.0,248301,248301,248301,248301
unique,NaN,1000,1002,5,NaN,NaN,NaN,7,NaN,1000,185528,42,NaN,7,23,39,68
top,NaN,HSB0196,PC-8001,logon,NaN,NaN,NaN,Monday,NaN,Hadley Sonya Bowen,ysmith@example.org,Salesman,NaN,2 - ResearchAndEngineering,2 - Sales,Unknown,Francis Brian Armstrong
freq,NaN,2596,2617,50165,NaN,NaN,NaN,86361,NaN,2544,31,50887,NaN,88365,52943,36544,11551
mean,2010-01-18 09:36:56.943604736,NaN,NaN,NaN,11.794254,11.321888,1.180293,NaN,0.044462,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
min,2010-01-02 06:49:00,NaN,NaN,NaN,0.000000,1.000000,1.000000,NaN,0.000000,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
25%,2010-01-04 05:35:43,NaN,NaN,NaN,9.000000,5.000000,1.000000,NaN,0.000000,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
50%,2010-01-12 14:05:13,NaN,NaN,NaN,12.000000,10.000000,1.000000,NaN,0.000000,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
75%,2010-01-29 17:25:16,NaN,NaN,NaN,14.000000,17.000000,1.000000,NaN,0.000000,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
max,2010-02-26 09:57:21,NaN,NaN,NaN,23.000000,31.000000,2.000000,NaN,1.000000,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,3.645105,7.447637,0.384432,NaN,0.206120,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN